import { css } from '@emotion/react';
import Head from 'next/head';
import type { FC, ReactNode } from 'react';
import { useEffect } from 'react';
import { useAccount, useConnect } from 'wagmi';

import { Logo, MetaMaskIcon } from '@/components';

import { ChainInfo, Header, MenuItem } from './styles';

type HomeLayoutType = {
  children: ReactNode;
};

const HomeLayout: FC<HomeLayoutType> = ({ children }) => {
  const { connect, connectors } = useConnect();
  const { address } = useAccount();

  const shortAddress = address?.slice(0, 6) + '...' + address?.slice(-4);

  useEffect(() => {
    connect({
      connector: connectors[0],
    });
  }, []);

  return (
    <>
      <Head>
        <title>PIX</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header>
        <div
          css={css`
            display: flex;
            align-items: center;
          `}
        >
          <Logo />
          <MenuItem href="/">Trade Betting</MenuItem>
        </div>
        <div
          css={css`
            display: flex;
            align-items: center;
          `}
        >
          <ChainInfo>
            <span
              css={css`
                position: relative;
                margin-right: 36px;
                &::after {
                  content: '';
                  position: absolute;
                  top: 50%;
                  right: -22px;
                  transform: translate(-50%, -50%);
                  width: 1px;
                  height: 16px;
                  background: #363a45;
                }
              `}
            >
              ETH
            </span>
            <div
              css={css`
                display: flex;
                align-items: center;
              `}
            >
              <MetaMaskIcon
                css={css`
                  position: relative;
                  padding-right: 11px;
                `}
              />
              {shortAddress}
            </div>
          </ChainInfo>
          <ChainInfo
            css={css`
              margin-left: 14px;
            `}
          >
            More
          </ChainInfo>
        </div>
      </Header>
      {children}
      {/* <main></main> */}
    </>
  );
};

export default HomeLayout;
