'use client';
import './globals.css';

import Web3Provider from '@qilin/wagmi-provider';
import { Inter } from 'next/font/google';
import { goerli } from 'wagmi/chains';

import { Header } from '@/components';

const inter = Inter({ subsets: ['latin'] });

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

const routes = [
  {
    path: '/',
    name: 'Trade',
  },
  {
    path: '/pool',
    name: 'Pool',
  },
];

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Web3Provider defaultChains={[goerli]} connectorNames={['MetaMask']}>
          <Header routes={routes} />
          {children}
        </Web3Provider>
      </body>
    </html>
  );
}
